kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
#Reduce memory consumption
#kotlin.native.binary.pagedAllocator=false
##Reduce string size in binary
#kotlin.native.binary.latin1Strings=true
# Not exactly sure how much the daemon needs, but defaults are not enough.
org.gradle.jvmargs=-Xmx4096m
# inlining optimization pass in the Kotlin IR compiler
#kotlin.native.binary.preCodegenInlineThreshold=80
## GC system
#kotlin.native.binary.gc=cms
## buffer overflow protection
#kotlin.native.binary.stackProtector=all
## Use malloc
#kotlin.native.binary.disableMmap=true