# BTH Config

# Core Config
sqliteDbPath = /home/akat/.local/share/bth/bth.db

# TUI Config
tuiShowExitCode = true
tuiShowCommandDuration = true
tuiShowHomeDirIndicator = true
tuiShowExecDirectory = false
tuiShowBTHId = false
tuiShowSudoIndicator = true

# Indicator Config
tuiHomeDirIndicator = '~'
tuiNoExitTimeIndicator = ''
tuiSudoIndicator = '#'
